// <auto-generated />
using Fittness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fittness.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240428110228_setHomeTable")]
    partial class setHomeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fittness.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Fittness.Data.Models.Palate1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Palates1");
                });

            modelBuilder.Entity("Fittness.Data.Models.PalateImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("PalatesImg");
                });

            modelBuilder.Entity("Fittness.Data.Models.PalateIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("item_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PalateIngredients");
                });

            modelBuilder.Entity("Fittness.Data.Models.PalateNutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carbohydrates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("protein")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PalateNutritions");
                });

            modelBuilder.Entity("Fittness.Data.Models.PalatePrepare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("step_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("step_7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PalatePrepares");
                });

            modelBuilder.Entity("Fittness.Data.Models.PalateRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("PreparationTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PalateRecipes");
                });

            modelBuilder.Entity("PickFitPor.Data.Models.hom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Home");
                });
#pragma warning restore 612, 618
        }
    }
}
